# Generated by Django 5.0.1 on 2025-11-20 00:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AIQuota",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "monthly_quota",
                    models.IntegerField(
                        default=20, help_text="Free monthly AI requests"
                    ),
                ),
                (
                    "additional_quota",
                    models.IntegerField(
                        default=0, help_text="Purchased additional requests"
                    ),
                ),
                ("used_this_month", models.IntegerField(default=0)),
                ("last_reset", models.DateTimeField(auto_now_add=True)),
                (
                    "price_per_request_usd",
                    models.DecimalField(decimal_places=3, default=0.1, max_digits=6),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_quota",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "AI Quota",
                "verbose_name_plural": "AI Quotas",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AISettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("default_monthly_quota", models.IntegerField(default=20)),
                (
                    "price_per_additional_request",
                    models.DecimalField(decimal_places=3, default=0.1, max_digits=6),
                ),
                ("enable_content_filter", models.BooleanField(default=True)),
                (
                    "strict_mode",
                    models.BooleanField(
                        default=False, help_text="More aggressive filtering"
                    ),
                ),
                ("max_requests_per_hour", models.IntegerField(default=10)),
                ("max_requests_per_day", models.IntegerField(default=50)),
                (
                    "model_name",
                    models.CharField(
                        default="assistant",
                        help_text="Internal use only",
                        max_length=100,
                    ),
                ),
                ("model_temperature", models.FloatField(default=0.7)),
                ("max_tokens", models.IntegerField(default=2000)),
                (
                    "system_prompt",
                    models.TextField(
                        default="You are a helpful coding assistant. Provide clear, concise code explanations and suggestions.",
                        help_text="Internal system prompt - never shown to users",
                    ),
                ),
                ("enabled", models.BooleanField(default=True)),
                ("maintenance_mode", models.BooleanField(default=False)),
                ("maintenance_message", models.TextField(blank=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "AI Settings",
                "verbose_name_plural": "AI Settings",
            },
        ),
        migrations.CreateModel(
            name="QuotaPurchase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.IntegerField(help_text="Number of requests purchased"),
                ),
                ("price_usd", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("credit_card", "Credit Card"),
                            ("paypal", "PayPal"),
                            ("crypto", "Cryptocurrency"),
                            ("admin_grant", "Admin Grant"),
                        ],
                        max_length=50,
                    ),
                ),
                ("payment_id", models.CharField(blank=True, max_length=200)),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("refunded", "Refunded"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quota_purchases",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Quota Purchase",
                "verbose_name_plural": "Quota Purchases",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AIUsageLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("prompt", models.TextField(help_text="User's question/prompt")),
                ("response", models.TextField(help_text="AI assistant's response")),
                ("tokens_used", models.IntegerField(default=0)),
                (
                    "response_time_ms",
                    models.IntegerField(
                        default=0, help_text="Response time in milliseconds"
                    ),
                ),
                (
                    "cost_usd",
                    models.DecimalField(decimal_places=4, default=0.0, max_digits=10),
                ),
                (
                    "context_type",
                    models.CharField(
                        choices=[
                            ("code_explanation", "Code Explanation"),
                            ("error_fix", "Error Fix"),
                            ("best_practice", "Best Practice Suggestion"),
                            ("general_chat", "General Chat"),
                        ],
                        default="general_chat",
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_usage_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "AI Usage Log",
                "verbose_name_plural": "AI Usage Logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="ai_assistan_user_id_eaaaea_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="ai_assistan_created_9d83d4_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ContentFilterLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("prompt", models.TextField(help_text="Blocked prompt")),
                (
                    "filter_reason",
                    models.CharField(
                        choices=[
                            ("political", "Political Content"),
                            ("pornographic", "Pornographic Content"),
                            ("hacking", "Hacking/Malicious Content"),
                            ("spam", "Spam"),
                            ("other", "Other Violation"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                ("reviewed", models.BooleanField(default=False)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("admin_notes", models.TextField(blank=True)),
                ("user_warned", models.BooleanField(default=False)),
                ("user_blocked", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_filters",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="content_filter_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Content Filter Log",
                "verbose_name_plural": "Content Filter Logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="ai_assistan_user_id_f7e41a_idx",
                    ),
                    models.Index(
                        fields=["reviewed", "-created_at"],
                        name="ai_assistan_reviewe_d88a1e_idx",
                    ),
                    models.Index(
                        fields=["severity", "-created_at"],
                        name="ai_assistan_severit_f78b2d_idx",
                    ),
                ],
            },
        ),
    ]
