# Generated by Django 5.0.1 on 2025-11-20 01:18

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MockSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "max_requests_per_hour",
                    models.IntegerField(
                        default=1000, help_text="Maximum requests per hour per user"
                    ),
                ),
                (
                    "max_endpoints_per_user",
                    models.IntegerField(
                        default=50,
                        help_text="Maximum mock endpoints per user (Free tier)",
                    ),
                ),
                (
                    "max_endpoints_pro",
                    models.IntegerField(
                        default=500, help_text="Maximum mock endpoints for Pro users"
                    ),
                ),
                (
                    "max_endpoints_enterprise",
                    models.IntegerField(
                        default=-1,
                        help_text="Maximum mock endpoints for Enterprise (-1 = unlimited)",
                    ),
                ),
                (
                    "log_retention_days",
                    models.IntegerField(
                        default=30, help_text="How long to keep request logs"
                    ),
                ),
                (
                    "enable_request_logging",
                    models.BooleanField(
                        default=True, help_text="Enable logging of all mock requests"
                    ),
                ),
                (
                    "enable_graphql",
                    models.BooleanField(
                        default=False, help_text="Enable GraphQL mocking"
                    ),
                ),
                (
                    "enable_soap",
                    models.BooleanField(
                        default=False, help_text="Enable SOAP/XML mocking"
                    ),
                ),
                ("enable_advanced_scenarios", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Mock Settings",
                "verbose_name_plural": "Mock Settings",
            },
        ),
        migrations.CreateModel(
            name="MockEndpoint",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Friendly name for this endpoint", max_length=255
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Description of what this mock endpoint does",
                    ),
                ),
                (
                    "path",
                    models.CharField(
                        help_text="URL path (e.g., /api/users/:id)", max_length=500
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("GET", "GET"),
                            ("POST", "POST"),
                            ("PUT", "PUT"),
                            ("PATCH", "PATCH"),
                            ("DELETE", "DELETE"),
                            ("HEAD", "HEAD"),
                            ("OPTIONS", "OPTIONS"),
                        ],
                        default="GET",
                        max_length=10,
                    ),
                ),
                (
                    "protocol",
                    models.CharField(
                        choices=[
                            ("rest", "REST/JSON"),
                            ("graphql", "GraphQL"),
                            ("soap", "SOAP/XML"),
                            ("toml", "TOML"),
                            ("yaml", "YAML"),
                        ],
                        default="rest",
                        max_length=20,
                    ),
                ),
                (
                    "status_code",
                    models.IntegerField(
                        default=200,
                        help_text="Default HTTP status code",
                        validators=[
                            django.core.validators.MinValueValidator(100),
                            django.core.validators.MaxValueValidator(599),
                        ],
                    ),
                ),
                (
                    "response_body",
                    models.TextField(
                        help_text="Response body template (supports variables like {{user_id}})"
                    ),
                ),
                (
                    "response_headers",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Custom response headers as JSON object",
                    ),
                ),
                (
                    "content_type",
                    models.CharField(
                        default="application/json",
                        help_text="Content-Type header value",
                        max_length=100,
                    ),
                ),
                (
                    "latency_min",
                    models.IntegerField(
                        default=0,
                        help_text="Minimum response latency in milliseconds",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "latency_max",
                    models.IntegerField(
                        default=0,
                        help_text="Maximum response latency in milliseconds (0 = no latency)",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "error_rate",
                    models.FloatField(
                        default=0.0,
                        help_text="Percentage of requests that should return errors (0-100)",
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(100.0),
                        ],
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this endpoint is active"
                    ),
                ),
                (
                    "enable_logging",
                    models.BooleanField(
                        default=True, help_text="Log requests to this endpoint"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "request_count",
                    models.IntegerField(
                        default=0, help_text="Total number of requests received"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mock_endpoints",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MockRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("method", models.CharField(max_length=10)),
                ("path", models.CharField(max_length=500)),
                ("query_params", models.JSONField(blank=True, default=dict)),
                ("headers", models.JSONField(blank=True, default=dict)),
                ("body", models.TextField(blank=True, help_text="Request body")),
                ("response_status", models.IntegerField()),
                ("response_body", models.TextField(blank=True)),
                ("response_headers", models.JSONField(blank=True, default=dict)),
                (
                    "response_time_ms",
                    models.IntegerField(help_text="Response time in milliseconds"),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "endpoint",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="request_logs",
                        to="api_mocking.mockendpoint",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MockResponse",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name for this response (e.g., 'Success', 'Not Found')",
                        max_length=255,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "condition_type",
                    models.CharField(
                        choices=[
                            ("default", "Default Response"),
                            ("query_param", "Query Parameter Match"),
                            ("header", "Header Match"),
                            ("body_field", "Request Body Field Match"),
                            ("random", "Random (Percentage-based)"),
                        ],
                        default="default",
                        max_length=50,
                    ),
                ),
                (
                    "condition_key",
                    models.CharField(
                        blank=True,
                        help_text="Key to check (param name, header name, or body field)",
                        max_length=255,
                    ),
                ),
                (
                    "condition_value",
                    models.TextField(
                        blank=True, help_text="Expected value for the condition"
                    ),
                ),
                (
                    "condition_probability",
                    models.FloatField(
                        default=100.0,
                        help_text="Probability % this response is returned (for random type)",
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(100.0),
                        ],
                    ),
                ),
                (
                    "status_code",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(100),
                            django.core.validators.MaxValueValidator(599),
                        ]
                    ),
                ),
                ("response_body", models.TextField(help_text="Response body template")),
                ("response_headers", models.JSONField(blank=True, default=dict)),
                (
                    "priority",
                    models.IntegerField(
                        default=0,
                        help_text="Higher priority responses are evaluated first",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "usage_count",
                    models.IntegerField(
                        default=0, help_text="How many times this response was used"
                    ),
                ),
                (
                    "endpoint",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responses",
                        to="api_mocking.mockendpoint",
                    ),
                ),
            ],
            options={
                "ordering": ["-priority", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MockScenario",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Scenario name (e.g., 'User Registration Flow')",
                        max_length=255,
                    ),
                ),
                ("description", models.TextField(help_text="What this scenario tests")),
                (
                    "scenario_data",
                    models.JSONField(
                        default=dict,
                        help_text="Additional scenario configuration (e.g., sequence, dependencies)",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "endpoints",
                    models.ManyToManyField(
                        help_text="Endpoints included in this scenario",
                        related_name="scenarios",
                        to="api_mocking.mockendpoint",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mock_scenarios",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="mockendpoint",
            index=models.Index(
                fields=["user", "is_active"], name="api_mocking_user_id_5d0cd1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="mockendpoint",
            index=models.Index(
                fields=["path", "method"], name="api_mocking_path_1c0a5f_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="mockendpoint",
            unique_together={("user", "path", "method")},
        ),
        migrations.AddIndex(
            model_name="mockrequest",
            index=models.Index(
                fields=["endpoint", "-created_at"],
                name="api_mocking_endpoin_53731e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="mockrequest",
            index=models.Index(
                fields=["-created_at"], name="api_mocking_created_28a671_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="mockresponse",
            index=models.Index(
                fields=["endpoint", "priority"], name="api_mocking_endpoin_7f5aaf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="mockscenario",
            index=models.Index(
                fields=["user", "is_active"], name="api_mocking_user_id_162faa_idx"
            ),
        ),
    ]
