# Generated by Django 5.0.1 on 2025-11-20 01:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_mocking", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MockApp",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="App name (e.g., 'E-commerce API')", max_length=255
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="What this app/project is for"
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True, help_text="Emoji or icon name", max_length=50
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="#6366f1", help_text="Hex color code", max_length=7
                    ),
                ),
                (
                    "base_url",
                    models.CharField(
                        blank=True,
                        help_text="Base URL for all endpoints",
                        max_length=500,
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=False, help_text="Allow public access to this app"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Mock App",
                "verbose_name_plural": "Mock Apps",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MockCollection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Collection name (e.g., 'User Management')",
                        max_length=255,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="What endpoints are in this collection"
                    ),
                ),
                (
                    "order",
                    models.IntegerField(
                        default=0, help_text="Display order within the app"
                    ),
                ),
                (
                    "folder",
                    models.CharField(
                        blank=True, help_text="Optional folder/category", max_length=255
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Mock Collection",
                "verbose_name_plural": "Mock Collections",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="MockEnvironment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Environment name (e.g., 'Development')",
                        max_length=255,
                    ),
                ),
                (
                    "variables",
                    models.JSONField(
                        default=dict, help_text="Key-value pairs of variables"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=False, help_text="Currently active environment"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Mock Environment",
                "verbose_name_plural": "Mock Environments",
                "ordering": ["name"],
            },
        ),
        migrations.AlterModelOptions(
            name="mockendpoint",
            options={"ordering": ["order", "-created_at"]},
        ),
        migrations.RemoveIndex(
            model_name="mockendpoint",
            name="api_mocking_user_id_5d0cd1_idx",
        ),
        migrations.RemoveIndex(
            model_name="mockscenario",
            name="api_mocking_user_id_162faa_idx",
        ),
        migrations.RemoveField(
            model_name="mockscenario",
            name="user",
        ),
        migrations.AddField(
            model_name="mockendpoint",
            name="order",
            field=models.IntegerField(
                default=0, help_text="Display order within collection"
            ),
        ),
        migrations.AddField(
            model_name="mockapp",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mock_apps",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="mockscenario",
            name="app",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="scenarios",
                to="api_mocking.mockapp",
            ),
        ),
        migrations.AddIndex(
            model_name="mockscenario",
            index=models.Index(
                fields=["app", "is_active"], name="api_mocking_app_id_4c2c30_idx"
            ),
        ),
        migrations.AddField(
            model_name="mockcollection",
            name="app",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="collections",
                to="api_mocking.mockapp",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="mockendpoint",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="mockendpoint",
            name="collection",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="endpoints",
                to="api_mocking.mockcollection",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="mockendpoint",
            unique_together={("collection", "path", "method")},
        ),
        migrations.AddIndex(
            model_name="mockendpoint",
            index=models.Index(
                fields=["collection", "is_active"],
                name="api_mocking_collect_eec072_idx",
            ),
        ),
        migrations.AddField(
            model_name="mockenvironment",
            name="app",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="environments",
                to="api_mocking.mockapp",
            ),
        ),
        migrations.RemoveField(
            model_name="mockendpoint",
            name="user",
        ),
    ]
