# Generated by Django 5.0.1 on 2025-11-12 14:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToolCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Tool Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AdPlacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_slug', models.CharField(db_index=True, max_length=100)),
                ('position', models.CharField(choices=[('top_banner', 'Top Banner'), ('sidebar_top', 'Sidebar Top'), ('sidebar_sticky', 'Sidebar Sticky'), ('in_content', 'In Content'), ('below_results', 'Below Results'), ('footer', 'Footer')], max_length=50)),
                ('ad_code', models.TextField(help_text='AdSense ad unit code')),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['tool_slug', 'priority'],
                'unique_together': {('tool_slug', 'position')},
            },
        ),
        migrations.CreateModel(
            name='ToolMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_slug', models.CharField(db_index=True, max_length=100, unique=True)),
                ('tool_name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('meta_title', models.CharField(max_length=200)),
                ('meta_description', models.CharField(max_length=300)),
                ('keywords', models.TextField(help_text='Comma-separated keywords')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tools', to='analytics.toolcategory')),
            ],
            options={
                'verbose_name_plural': 'Tool Metadata',
                'ordering': ['category', 'order', 'tool_name'],
            },
        ),
        migrations.CreateModel(
            name='ToolUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_slug', models.CharField(db_index=True, max_length=100)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('session_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('processing_time', models.FloatField(blank=True, help_text='Processing time in milliseconds', null=True)),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'Tool Usage Records',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tool_slug', '-created_at'], name='analytics_t_tool_sl_fcd916_idx'), models.Index(fields=['session_id', '-created_at'], name='analytics_t_session_62caff_idx')],
            },
        ),
    ]
