# Generated by Django 5.0.1 on 2025-11-19 15:28

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.CharField(
                        editable=False, max_length=32, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "subscription_tier",
                    models.CharField(
                        choices=[
                            ("free", "Free"),
                            ("pro", "Pro"),
                            ("enterprise", "Enterprise"),
                        ],
                        default="free",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owned_teams",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "teams",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TeamAPIKey",
            fields=[
                (
                    "id",
                    models.CharField(
                        editable=False, max_length=32, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("key", models.CharField(db_index=True, max_length=64, unique=True)),
                ("key_prefix", models.CharField(max_length=8)),
                ("last_used", models.DateTimeField(blank=True, null=True)),
                ("total_requests", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_team_api_keys",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="api_keys",
                        to="teams.team",
                    ),
                ),
            ],
            options={
                "db_table": "team_api_keys",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TeamAuditLog",
            fields=[
                (
                    "id",
                    models.CharField(
                        editable=False, max_length=32, primary_key=True, serialize=False
                    ),
                ),
                ("action", models.CharField(max_length=100)),
                ("resource_type", models.CharField(max_length=50)),
                (
                    "resource_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("details", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_logs",
                        to="teams.team",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="team_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "team_audit_logs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TeamInvitation",
            fields=[
                (
                    "id",
                    models.CharField(
                        editable=False, max_length=32, primary_key=True, serialize=False
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254,
                        validators=[django.core.validators.EmailValidator()],
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("owner", "Owner"),
                            ("admin", "Admin"),
                            ("developer", "Developer"),
                            ("viewer", "Viewer"),
                        ],
                        default="developer",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("declined", "Declined"),
                            ("expired", "Expired"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "invited_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sent_invitations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invitations",
                        to="teams.team",
                    ),
                ),
            ],
            options={
                "db_table": "team_invitations",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TeamMember",
            fields=[
                (
                    "id",
                    models.CharField(
                        editable=False, max_length=32, primary_key=True, serialize=False
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("owner", "Owner"),
                            ("admin", "Admin"),
                            ("developer", "Developer"),
                            ("viewer", "Viewer"),
                        ],
                        default="developer",
                        max_length=20,
                    ),
                ),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                (
                    "last_active",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="teams.team",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "team_members",
                "ordering": ["role", "-joined_at"],
            },
        ),
        migrations.CreateModel(
            name="TeamUsageLog",
            fields=[
                (
                    "id",
                    models.CharField(
                        editable=False, max_length=32, primary_key=True, serialize=False
                    ),
                ),
                ("endpoint", models.CharField(max_length=255)),
                ("method", models.CharField(max_length=10)),
                ("tool_slug", models.CharField(blank=True, max_length=100)),
                ("tool_name", models.CharField(blank=True, max_length=100)),
                ("status_code", models.IntegerField()),
                ("response_time_ms", models.FloatField()),
                ("file_size_bytes", models.BigIntegerField(default=0)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "api_key",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="usage_logs",
                        to="teams.teamapikey",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usage_logs",
                        to="teams.team",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="team_usage_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "team_usage_logs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="team",
            index=models.Index(
                fields=["owner", "created_at"], name="teams_owner_i_5054ae_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="teamapikey",
            index=models.Index(
                fields=["team", "is_active"], name="team_api_ke_team_id_5bd787_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="teamauditlog",
            index=models.Index(
                fields=["team", "-created_at"], name="team_audit__team_id_6c53d2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="teamauditlog",
            index=models.Index(
                fields=["user", "-created_at"], name="team_audit__user_id_7f4c92_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="teamauditlog",
            index=models.Index(fields=["action"], name="team_audit__action_ddb2d8_idx"),
        ),
        migrations.AddIndex(
            model_name="teaminvitation",
            index=models.Index(
                fields=["team", "status"], name="team_invita_team_id_d0b794_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="teaminvitation",
            index=models.Index(
                fields=["email", "status"], name="team_invita_email_f39c53_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="teammember",
            index=models.Index(
                fields=["team", "user"], name="team_member_team_id_61cdbf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="teammember",
            index=models.Index(
                fields=["user", "team"], name="team_member_user_id_e51291_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="teammember",
            unique_together={("team", "user")},
        ),
        migrations.AddIndex(
            model_name="teamusagelog",
            index=models.Index(
                fields=["team", "-created_at"], name="team_usage__team_id_3e4f9b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="teamusagelog",
            index=models.Index(
                fields=["user", "-created_at"], name="team_usage__user_id_036566_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="teamusagelog",
            index=models.Index(
                fields=["tool_slug"], name="team_usage__tool_sl_707417_idx"
            ),
        ),
    ]
